SCR_EditorActionList {
 m_Actions {
  GRAD_GMOpenArsenalAction "{216C37D13FDF7D63}" {
   m_Info SCR_UIInfo "{071D19BAB7D4E1E1}" {
    Name "Open Arsenal"
    Description "Edit this unit's loadout in the GRAD arsenal."
    Icon "{2EEBBBCA36DD775F}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Pistols.edds"
   }
   m_iOrder 12
  }
  GRAD_GMCopyLoadoutAction "{482F09941D6A5930}" {
   m_Info SCR_UIInfo "{5A582D3022609C04}" {
    Name "Copy Loadout"
    Description "Copy this unit's loadout to the GRAD clipboard."
    Icon "{2EEBBBCA36DD775F}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Pistols.edds"
   }
   m_iOrder 13
  }
  GRAD_GMPasteLoadoutAction "{0C571A9E366027A2}" {
   m_Info SCR_UIInfo "{0DCB1B582454D855}" {
    Name "Paste Loadout"
    Description "Apply the GRAD clipboard loadout to selected unit(s)."
    Icon "{2EEBBBCA36DD775F}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Pistols.edds"
   }
   m_iOrder 14
  }
 }
}
