SCR_MissionHeader {
 World "{8A7CA49CD4A81136}Worlds/test.ent"
 m_sName "<Insert world name>"
 m_sAuthor "<Insert your name>"
 m_sDescription "<Insert world description>"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}